function [roi_names,roi_fnames,roi_no] = get_roi_list()
    %% Get a list of ROIs
    % @author: pdzialecka
    
    % add medial and lateral cortex ROIs?

    %%
    roi_names = {'Right Hipp CA1','Right Hipp CA3','Right Hipp DG',...
        'Left Hipp CA1','Left Hipp CA3','Left Hipp DG',...
        'Right Cortex',...
        'Left Cortex',...
        'Right Auditory Cortex'};
    
    roi_no = length(roi_names);
    
    roi_fnames = {'hipp_R_CA1','hipp_R_CA3','hipp_R_DG',...
                'hipp_L_CA1','hipp_L_CA3','hipp_L_DG',...
                'cortex_R',...
                'cortex_L',...
                'cortex_AU_R'};
    
end
